### ISSUE TITLE
[SMRT] Can't use VRF & ChainlinkClient

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/chainlink#3747] opened 2020-12-03 16:50 UTC
**Description**
When inheriting ChainlinkClient and VRFConsumerBase, we get a conflict.

**Steps to Reproduce**
1. [Hit this link](https://remix.ethereum.org/#gist=a9f7aa77650de07586e0e6241193a3ae&optimize=true&version=soljson-v0.6.6+commit.6c089d02.js&runs=200&evmVersion=null)
2. Go to the gist
3. Hit compile
See error

**Additional Information**
Error:
```
https://raw.githubusercontent.com/smartcontractkit/chainlink/master/evm-contracts/src/v0.6/interfaces/LinkTokenInterface.sol:3:1: The previous declaration is here: interface LinkTokenInterface { ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by alexroan** [comment] 2020-12-04 18:05
This is a duplicate of #3175

**Closed by alexroan** 2020-12-04 18:05 UTC
Labels: duplicate
