### ISSUE TITLE
[NODE] Job Error section crashes the web application

### ISSUE THREAD

**Issue by mario-purestake** [smartcontractkit/chainlink#3504] opened 2020-10-23 11:51 UTC
**Description**
Web application crashes when trying to access the **Errors (1)** tab from a job page.

**Basic Information**
When creating a job, we are experiencing an error related to the subscription that the node's performing to the Oracle's `Oracle Request` event. How we get this error is not related to the current issue, the important part is that a job **has** an error. The job is created and appears in the job list. If we navigate to its page, we can see (image below) that the `Errors` tab has a `(1)`, so it detects that an error happened and it's related to the job.

![image](https://user-images.githubusercontent.com/66425016/96998654-1df4d780-1534-11eb-9ed1-dce41c388e72.png)

If we click on this tab, we go to the error page (we can see the `error/` path in the URL), but we get a white screen and going back to the previous job page is not possible. The only way to use the web again is reintroducing the URL/IP of the node in the browser.

- Network: Moonbeam Alphanet
- Blockchain Client: Moonbeam v0.2.1
- Go Version: ? (we are using the image `smartcontract/chainlink:0.9.2`)
- Operating System: Ubuntu 18.04
- Commit: 

```shell
    Starting Chainlink Node 0.9.2 at commit 1f4517b5c0139c3c6545a28e20e74001d5181099
```
- Hosting Provider: GCP Kubernetes cluster
- Startup Command: 

```shell
    chainlink local node -p /chainlink/.password -a /chainlink/.api
```

**Environment Variables**
```shell
ACCOUNT_ADDRESS: (...)
ALLOW_ORIGINS: *
BLOCK_BACKFILL_DEPTH: 10
BRIDGE_RESPONSE_URL: 
ETH_CHAIN_ID: 43
CLIENT_NODE_URL: http://localhost:6688
DATABASE_TIMEOUT: 500ms
DEFAULT_HTTP_LIMIT: 32768
DEFAULT_HTTP_TIMEOUT: 15s
CHAINLINK_DEV: false
ENABLE_BULLETPROOF_TX_MANAGER: true
ENABLE_EXPERIMENTAL_ADAPTERS: false
ETH_BALANCE_MONITOR_BLOCK_DELAY: 1
ETH_DISABLED: false
ETH_FINALITY_DEPTH: 50
ETH_GAS_BUMP_THRESHOLD: 3
ETH_GAS_BUMP_TX_DEPTH: 10
ETH_GAS_BUMP_WEI: 5000000000
ETH_GAS_LIMIT_DEFAULT: 500000
ETH_GAS_PRICE_DEFAULT: 20000000000
ETH_HEAD_TRACKER_HISTORY_DEPTH: 100
ETH_HEAD_TRACKER_MAX_BUFFER_SIZE: 3
ETH_MAX_GAS_PRICE_WEI: 1500000000000
ETH_URL: wss://wss.testnet.moonbeam.network
ETH_SECONDARY_URL: 
EXPLORER_URL: 
FEATURE_EXTERNAL_INITIATORS: false
FEATURE_FLUX_MONITOR: true
FLAGS_CONTRACT_ADDRESS: 
GAS_UPDATER_BLOCK_DELAY: 3
GAS_UPDATER_BLOCK_HISTORY_SIZE: 24
GAS_UPDATER_ENABLED: false
GAS_UPDATER_TRANSACTION_PERCENTILE: 60
JSON_CONSOLE: false
LINK_CONTRACT_ADDRESS: (...)
LOG_LEVEL: debug
LOG_SQL_MIGRATIONS: true
LOG_SQL: false
LOG_TO_DISK: true
MAX_RPC_CALLS_PER_SECOND: 500
MAXIMUM_SERVICE_DURATION: 8760h0m0s
MIN_INCOMING_CONFIRMATIONS: 3
MIN_OUTGOING_CONFIRMATIONS: 2
MINIMUM_SERVICE_DURATION: 
MINIMUM_CONTRACT_PAYMENT: 0.000000000000000000
MINIMUM_REQUEST_EXPIRATION: 300
OPERATOR_CONTRACT_ADDRESS: 
CHAINLINK_PORT: 6688
REAPER_EXPIRATION: 240h0m0s
REPLAY_FROM_BLOCK: -1
ROOT: chainlink
SECURE_COOKIES: false
SESSION_TIMEOUT: 16h39m0s
CHAINLINK_TLS_HOST: 
CHAINLINK_TLS_PORT: 0
CHAINLINK_TLS_REDIRECT: false
CHAINLINK_TX_ATTEMPT_LIMIT: 10
```

**Steps to Reproduce**
1. Create a job. Job subscription will fail.
2. Navigate to job page.
3. Click on **Errors (1)**.

**Additional Information**
None

**Comment by DeividasK** [comment] 2020-10-29 14:03
Hey @mario-purestake, thanks for raising this issue. Unfortunately, I'm unable to reproduce it, you can see my attempt below:
![Job spec errors](https://user-images.githubusercontent.com/9297294/97583910-5cd0d480-19ef-11eb-81d6-a5266b0dccf8.gif)

Is there any output in the browser's console?

**Comment by mario-purestake** [comment] 2020-10-30 11:30
Hey @DeividasK, thanks for replying. Yes, I can see an error on the browser's console:

```shell
RangeError: date value is not finite in DateTimeFormat.format()
    default http://localhost:6688/main.e92608bc29d20ec97425.js:94
    value http://localhost:6688/main.e92608bc29d20ec97425.js:94
    value http://localhost:6688/main.e92608bc29d20ec97425.js:94
    Zi http://localhost:6688/main.e92608bc29d20ec97425.js:61
    Xi http://localhost:6688/main.e92608bc29d20ec97425.js:61
    Os http://localhost:6688/main.e92608bc29d20ec97425.js:61
    Du http://localhost:6688/main.e92608bc29d20ec97425.js:61
    Yu http://localhost:6688/main.e92608bc29d20ec97425.js:61
    Mu http://localhost:6688/main.e92608bc29d20ec97425.js:61
    Xa http://localhost:6688/main.e92608bc29d20ec97425.js:61
    unstable_runWithPriority http://localhost:6688/main.e92608bc29d20ec97425.js:69
    Ga http://localhost:6688/main.e92608bc29d20ec97425.js:61
    Xa http://localhost:6688/main.e92608bc29d20ec97425.js:61
    Qa http://localhost:6688/main.e92608bc29d20ec97425.js:61
    _u http://localhost:6688/main.e92608bc29d20ec97425.js:61
    enqueueSetState http://localhost:6688/main.e92608bc29d20ec97425.js:61
    setState http://localhost:6688/main.e92608bc29d20ec97425.js:25
    value http://localhost:6688/main.e92608bc29d20ec97425.js:6
    update http://localhost:6688/main.e92608bc29d20ec97425.js:6
    value http://localhost:6688/main.e92608bc29d20ec97425.js:6
    (...)
```

I recorded the process too if that helps you in any way:
![Screencast 2020-10-30 12:23:05](https://user-images.githubusercontent.com/66425016/97700144-a121aa80-1aab-11eb-9779-4725f32b39e1.gif)

**Comment by DeividasK** [comment] 2020-11-06 10:06
Just a quick update - I've added it as a bug to our backlog, but because it doesn't happen on all errors I rated it as low priority.

**Comment by DeividasK** [comment] 2020-12-01 20:17
Closing this as I believe it is fixed in the latest release. Feel free to re-open if it isn't.

**Closed by DeividasK** 2020-12-01 20:17 UTC
Labels: bug

**Comment by mario-purestake** [comment] 2020-12-02 15:04
I'll take a look at it again in the latest version, thanks!
