### ISSUE TITLE
Snapshot response filled with null and snapshot show gives 404

### ISSUE THREAD

**Issue by TaylanT** [smartcontractkit/chainlink#9] opened 2017-11-12 14:39 UTC
I have setup a chainlink node with the docker image. Created an assingment. But a a POST to .../xid/snapshots responds with everything null. For example: 

`{
    "assignmentXID": "387108e6-70c1-428e-9193-78fbbc5db7ae",
    "description": null,
    "descriptionURL": null,
    "details": null,
    "status": null,
    "summary": null,
    "value": null,
    "xid": "f5f499f4-7545-44c9-9e76-07e491f62b6e"
}`

 But when I do a query on ../assignments/xid the snapshots are shown. The snapshot is created. 

Additionaly a GET to /snapshots/xid (tried all snapshots xids) gives me a 404.

Any ideas?

**Comment by se3000** [comment] 2017-11-15 23:25
When the snapshot is initially created, it hasn't fully processed the pipeline of adapters, so final information like `description` and `details` are not yet available. This is because some adapters may take a long time to complete, and leaving the request hanging until they all finish could potentially block other incoming connections. The snapshot creation method creates the initial snapshot, but the remaining fields are not filled in the assignment's final adapter has completed its work.

If the fields are filled in when you query the assignment, that is probably because the assignment has had enough time to finish processing its pipeline. The built in adapters all run relatively quickly, but to be consistent across all adapter types the assignment creation method returns before processing begins.

As for the snapshots GET method not working, that looks like a regression. I'll look into that and push a fix soon, either to the code or the documentation.

**Comment by se3000** [comment] 2017-11-18 01:17
Ok, thanks for reporting. Just pushed a fix and that method now works. Closing the issue, but feel free to reopen if you have further questions or issues.

**Closed by se3000** 2017-11-18 01:17 UTC
