### ISSUE TITLE
[NODE] Crash trying to update to 0.9.4 - add warning when migrating to versions above 0.9.2 of Chainlink

### ISSUE THREAD

**Issue by hershkoy** [smartcontractkit/chainlink#3637] opened 2020-11-15 11:03 UTC
**Basic Information**
Got this error when trying to upgrade from 0.9.2 to 0.9.4

```
2020-11-15T10:58:34Z [WARN]  pq: syntax error at or near "INCLUDE"              migration1603816329/migrate.go:12 
2020-11-15T10:58:34Z [DEBUG] 
CREATE INDEX idx_pipeline_task_runs_optimise_find_predecessor_unfinished_runs ON pipeline_task_runs (pipeline_task_spec_id, pipeline_run_id) INCLUDE (id, finished_at);
CREATE INDEX idx_pipeline_task_runs_optimise_find_results ON pipeline_task_runs (pipeline_run_id);
 gormigrate.v1@v1.6.0/gormigrate.go:364 rows_affected=0 time=0.004170511 
2020-11-15T10:58:34Z [FATAL] Unable to initialize ORM: pq: syntax error at or near "INCLUDE"
error running migrations
github.com/smartcontractkit/chainlink/core/store/migrations.MigrateTo
	/chainlink/core/store/migrations/migrate.go:436
github.com/smartcontractkit/chainlink/core/store/migrations.Migrate
	/chainlink/core/store/migrations/migrate.go:410
github.com/smartcontractkit/chainlink/core/store.initializeORM.func1
	/chainlink/core/store/store.go:184
github.com/smartcontractkit/chainlink/core/store/orm.(*ORM).RawDB
	/chainlink/core/store/orm/orm.go:1530
github.com/smartcontractkit/chainlink/core/store.initializeORM
	/chainlink/core/store/store.go:183
github.com/smartcontractkit/chainlink/core/store.newStoreWithKeyStore
	/chainlink/core/store/store.go:78
github.com/smartcontractkit/chainlink/core/store.NewStore
	/chainlink/core/store/store.go:57
github.com/smartcontractkit/chainlink/core/services/chainlink.NewApplication
	/chainlink/core/services/chainlink/application.go:97
github.com/smartcontractkit/chainlink/core/cmd.ChainlinkAppFactory.NewApplication
	/chainlink/core/cmd/client.go:84
github.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode
	/chainlink/core/cmd/local_client.go:53
github.com/urfave/cli.HandleAction
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526
github.com/urfave/cli.Command.Run
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174
github.com/urfave/cli.(*App).RunAsSubcommand
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:407
github.com/urfave/cli.Command.startApp
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:373
github.com/urfave/cli.Command.Run
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:102
github.com/urfave/cli.(*App).Run
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279
main.Run
	/chainlink/core/main.go:18
main.main
	/chainlink/core/main.go:12
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
initializeORM#Migrate
github.com/smartcontractkit/chainlink/core/store.initializeORM
	/chainlink/core/store/store.go:187
github.com/smartcontractkit/chainlink/core/store.newStoreWithKeyStore
	/chainlink/core/store/store.go:78
github.com/smartcontractkit/chainlink/core/store.NewStore
	/chainlink/core/store/store.go:57
github.com/smartcontractkit/chainlink/core/services/chainlink.NewApplication
	/chainlink/core/services/chainlink/application.go:97
github.com/smartcontractkit/chainlink/core/cmd.ChainlinkAppFactory.NewApplication
	/chainlink/core/cmd/client.go:84
github.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode
	/chainlink/core/cmd/local_client.go:53
github.com/urfave/cli.HandleAction
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526
github.com/urfave/cli.Command.Run
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174
github.com/urfave/cli.(*App).RunAsSubcommand
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:407
github.com/urfave/cli.Command.startApp
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:373
github.com/urfave/cli.Command.Run
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:102
github.com/urfave/cli.(*App).Run
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279
main.Run
	/chainlink/core/main.go:18
main.main
	/chainlink/core/main.go:12
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374 store/store.go:80                stacktrace=github.com/smartcontractkit/chainlink/core/store.newStoreWithKeyStore
	/chainlink/core/store/store.go:80
github.com/smartcontractkit/chainlink/core/store.NewStore
	/chainlink/core/store/store.go:57
github.com/smartcontractkit/chainlink/core/services/chainlink.NewApplication
	/chainlink/core/services/chainlink/application.go:97
github.com/smartcontractkit/chainlink/core/cmd.ChainlinkAppFactory.NewApplication
	/chainlink/core/cmd/client.go:84
github.com/smartcontractkit/chainlink/core/cmd.(*Client).RunNode
	/chainlink/core/cmd/local_client.go:53
github.com/urfave/cli.HandleAction
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526
github.com/urfave/cli.Command.Run
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174
github.com/urfave/cli.(*App).RunAsSubcommand
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:407
github.com/urfave/cli.Command.startApp
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:373
github.com/urfave/cli.Command.Run
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:102
github.com/urfave/cli.(*App).Run
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279
main.Run
	/chainlink/core/main.go:18
main.main
	/chainlink/core/main.go:12
runtime.main
	/usr/local/go/src/runtime/proc.go:204 
```

- Network: Kovan
- Blockchain Client: Infura
- Operating System: Ubuntu 18.04.5 LTS
- Commit: Starting Chainlink Node 0.9.4 at commit b7d22afdae61fc9146136e8518c221d406d10d6d cmd/local_client.go:51  
- Hosting Provider:  self-hosted
- Startup Command: chainlink local n -p /chainlink/.password -a /chainlink/.api

**Environment Variables**
```ALLOW_ORIGINS=*
DATABASE_TIMEOUT=0
TLS_CERT_PATH=/chainlink/tls/server.crt
TLS_KEY_PATH=/chainlink/tls/server.key
DATABASE_URL=postgresql://...................
ETH_CHAIN_ID=42
ETH_URL=wss://kovan.infura.io/ws/v3/.........................
LINK_CONTRACT_ADDRESS=0xa36085F69e2889c224210F603D836748e7dC0088
LOG_LEVEL=debug
MIN_OUTGOING_CONFIRMATIONS=2
GAS_UPDATER_ENABLED=true
LOG_TO_DISK=false
ROOT=/chainlink
```

**Comment by willianpaixao** [comment] 2020-11-17 11:43
@hershkoy you mentioned on Discord that this was caused by using Postgres version 10, right?

**Comment by PatrickAlphaC** [comment] 2020-11-19 02:34
Thanks @willianpaixao, yes, you hit the nail on the head! v0.9.4 and newer will no longer work on psql versions 10 and under

**Comment by willianpaixao** [comment] 2020-11-19 08:55
@PatrickAlphaC is it possible to try/catch this error and warn the user about the version rather than crash like this?

**Comment by PatrickAlphaC** [comment] 2020-11-19 16:52
Good question, perhaps we edit and reopen the issue to clarify what we are trying to accomplish?

**Comment by willianpaixao** [comment] 2020-11-19 19:39
@PatrickAlphaC yes, that would be good.

**Comment by PatrickAlphaC** [comment] 2020-11-19 19:59
Reopened, thanks @willianpaixao

**Comment by PatrickAlphaC** [comment] 2021-05-05 15:06
Closing. We are quickly outpacing the 0.9 version of the Chainlink node.

**Closed by PatrickAlphaC** 2021-05-05 15:06 UTC
Labels: enhancement, good first issue
