### ISSUE TITLE
[NODE] Node installation getting stuck on `belt compile all` step of `make install`

### ISSUE THREAD

**Issue by bamzedev** [smartcontractkit/chainlink#4514] opened 2021-06-03 18:36 UTC
**Description**
The installation is getting stuck on `$ belt compile all` step of the `make install` script.

**Basic Information**
Console output after running `$ make install`:
`$ make install
yarn install --frozen-lockfile
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@^0.5.19"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@^0.5.17"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@0.5.12"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@0.5.12"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@^0.5.19"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@^0.5.19"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@^0.5.19"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@^0.5.19"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@^0.5.19"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@~0.5.19"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@^0.5.19"
warning Resolution field "source-map-support@0.5.16" is incompatible with requested version "source-map-support@^0.4.15"
success Already up-to-date.
$ patch-package
patch-package 6.2.1
Applying patches...
@0x/sol-compiler@4.0.8 ✔
Done in 1.36s.
./tools/bin/restore-solc-cache
yarn setup:chainlink
yarn run v1.22.4
$ yarn wsrun -mre -p @chainlink/contracts -p @chainlink/operator-ui -t setup
$ D:\Development\Workspaces\chainlink\node_modules\.bin\wsrun -mre -p @chainlink/contracts -p @chainlink/operator-ui -t setup
@chainlink/operator-ui
 | $ tsc -b
@chainlink/test-helpers
 | $ yarn generate-typings && tsc -b
@chainlink/belt
 | $ tsc -b
@chainlink/test-helpers
 | $ typechain --target ethers-v4 --outDir src/generated src/LinkToken.json
 | ts-gen: Running TypeChain
 | ts-gen: src/LinkToken.json matched 1 files.
 | ts-gen: Processing src\LinkToken.json
 | ts-gen: Writing file: src\generated\LinkToken.d.ts
 | ts-gen: Writing file: src\generated\factories\LinkToken__factory.ts
 | ts-gen: Writing file: src\generated\index.d.ts
 | ts-gen: 💎 All done! Generated files: 3
@chainlink/contracts
 | $ yarn compile:clean && tsc -b tsconfig.test.json tsconfig.ethers.json
 | $ yarn clean && yarn compile
 | $ tsc -b --clean tsconfig.test.json tsconfig.ethers.json && rm -rf abi ethers truffle solc
 | $ belt compile all
 | Creating directory at abi\v0.4...
 | Creating directory at abi\v0.5...
 | Creating directory at abi\v0.6...
 | Creating directory at abi\v0.7...
`

- Network: [NA]
- Blockchain Client: [Geth v1.10.3]
- Go Version: [ go1.16.4 windows/amd64]
- Operating System: [Windows 10]
- Commit: [commit 6604a647da8af2e0daafb652af13a420b7128f9c (HEAD -> master, tag: v0.10.7, origin/master]
- Hosting Provider: [self-hosted]
- Startup Command: [make install]

**Environment Variables**

**Steps to Reproduce**
1. Open Git Bash
2. Navigate to chainlink folder
3. run `make install`

**Additional Information**

**Comment by PatrickAlphaC** [comment] 2021-06-03 21:46
How long did you wait? Could you wait up to 30 minutes?

**Comment by bamzedev** [comment] 2021-06-03 22:32
It's been some hours now, still stuck.

**Comment by PatrickAlphaC** [comment] 2021-06-04 14:25
what version of node are you using?

**Comment by bamzedev** [comment] 2021-06-04 15:05
12.18.3

**Comment by PatrickAlphaC** [comment] 2021-06-05 15:13
Hmm... is there any other information you can provide? I'm not able to reproduce the issue.

**Comment by bamzedev** [comment] 2021-06-05 15:32
Not sure what to provide :/. Happy screen share or whatever could be useful.

**Comment by chiku524** [comment] 2021-06-17 22:20
Hi, was there ever a solution for this issue? Same thing happens to me. Using v12.18.0 for node.

**Comment by pappas999** [comment] 2021-06-18 00:23
hi @chiku524 , can you try with NodeJS 12.18.4, and see if you still have the same issue?

If it still happens, let us know what O/S your running, what version of Go, and which version of the Node you're trying to build

**Comment by chiku524** [comment] 2021-06-18 23:32
Hey, so it looks changing the NodeJS version didn't do anything.

OS: Windows 10
Go version: 1.16.5 windows/amd64
Version of the node: Not sure. 

After running make install, it says `$patch-package 6.4.7` somewhere in the terminal, not sure if that helps though.

I basically followed the installation steps on the README, don't think I changed any of the code.

**Comment by pappas999** [comment] 2021-06-21 04:45
thanks for trying that @chiku524 . Can you please change your version of Go to 1.15 and then try again? I've been able to successfully do a build on windows with 1.15. Also leave NodeJS at 12.18.4

**Comment by chiku524** [comment] 2021-06-21 17:42
Yeah sure, I don't mind but I'm having trouble switching versions of Go. What's the best way I can do that?

I tried installing GVM but couldn't get it to work (for Windows 10). 
I also tried to follow this: (https://golang.org/doc/manage-install) but it doesn't give steps on how to use the specific version you want to.

**Comment by loks2cool** [comment] 2021-10-03 19:05
Hi,

 I have this issue with Mac OS - M1 Chip version. 
Using 12.18.4 but Go Lang 1.16.

Tried using 1.15 version, but it shows deprecated in my machine.

Warning: go@1.15 has been deprecated because it is not supported upstream!
go@1.15: The x86_64 architecture is required for this software.
Error: go@1.15: An unsatisfied requirement failed this build.

is there any other workaround?, please suggest

**Comment by pappas999** [comment] 2021-10-04 12:08
@chiku524 try uninstalling your old verison and installing 1.15

@loks2cool 1.16 isn't officially supported yet. Suggest trying to get 1.15 working. Sounds like your issue is specific to Go and your o/s, you may need to raise a question or issue on StackOverflow to try get help on getting 1.15 installed

**Comment by PatrickAlphaC** [comment] 2022-01-10 17:27
Closing for now. Feel free to follow up.

**Closed by PatrickAlphaC** 2022-01-10 17:27 UTC
Labels: investigating
